name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm pack
      - run: npm install -g golem-sdk-yagna-*.tgz
      - run: yagna -V
      - run: gftp -V
